<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://example.com/pokeapi/pokemons"
           xmlns:tns="http://example.com/pokeapi/pokemons"
           elementFormDefault="qualified">

    <xs:element name="getPokemonRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="getPokemonResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string"/>
                <xs:element name="height" type="xs:int"/>
                <xs:element name="weight" type="xs:int"/>
                <xs:element name="baseExperience" type="xs:int"/>
                <xs:element name="types" type="xs:string" maxOccurs="unbounded"/>
                <xs:element name="abilities" type="xs:string" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>
